//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QrSortable.Components.UiFunctionality.Localization
 {
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {}
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QrSortable.Components.UiFunctionality.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }



        /// <summary>
        ///   Looks up a localized string similar to Dialog Processing Message Text!!.
        /// </summary>
        public static string Dialog_Processing
        {
            get
            {
                return ResourceManager.GetString("Dialog_Processing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog Conformation Text!!.
        /// </summary>
        public static string Dialog_Conformation
        {
            get
            {
                return ResourceManager.GetString("Dialog_Conformation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog InternetConnection Message Text!!.
        /// </summary>
        public static string Dialog_InternetConnection_Message
        {
            get
            {
                return ResourceManager.GetString("Dialog_InternetConnection_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog InternetConnection Title Text!!.
        /// </summary>
        public static string Dialog_InternetConnection_Title
        {
            get
            {
                return ResourceManager.GetString("Dialog_InternetConnection_Title", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Dialog ConfirmationMessage Text!!.
        /// </summary>
        public static string Dialog_ConfirmationMessage_Text
        {
            get
            {
                return ResourceManager.GetString("Dialog_ConfirmationMessage_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog information Text!!.
        /// </summary>
        public static string Dialog_InformationText
        {
            get
            {
                return ResourceManager.GetString("Dialog_InformationText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog Error Text!!.
        /// </summary>
        public static string Dialog_Error
        {
            get
            {
                return ResourceManager.GetString("Dialog_Error", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Dialog Cancel Text!!.
        /// </summary>
        public static string Dialog_Cancel_Text
        {
            get
            {
                return ResourceManager.GetString("Dialog_Cancel_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog OK Text!!.
        /// </summary>
        public static string Dialog_OK_Text
        {
            get
            {
                return ResourceManager.GetString("Dialog_OK_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to paid Text!!.
        /// </summary>
        public static string General_PaidText
        {
            get
            {
                return ResourceManager.GetString("General_PaidText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to pending Text!!.
        /// </summary>
        public static string General_PendingText
        {
            get
            {
                return ResourceManager.GetString("General_PendingText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to open Text!!.
        /// </summary>
        public static string General_OpenText
        {
            get
            {
                return ResourceManager.GetString("General_OpenText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to failed Text!!.
        /// </summary>
        public static string General_FailedText
        {
            get
            {
                return ResourceManager.GetString("General_FailedText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to pending Text!!.
        /// </summary>
        public static string General_PendingStatusText
        {
            get
            {
                return ResourceManager.GetString("General_PendingStatusText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to download Text!!.
        /// </summary>
        public static string General_DownloadStatusText
        {
            get
            {
                return ResourceManager.GetString("General_DownloadStatusText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to cancel payment Text!!.
        /// </summary>
        public static string General_CancelPaymentText
        {
            get
            {
                return ResourceManager.GetString("General_CancelPaymentText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to unknown payment Text!!.
        /// </summary>
        public static string General_UnknownPaymentText
        {
            get
            {
                return ResourceManager.GetString("General_UnknownPaymentText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to email Text!!.
        /// </summary>
        public static string General_EmailText
        {
            get
            {
                return ResourceManager.GetString("General_EmailText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to sucess Text!!.
        /// </summary>
        public static string General_SucessText
        {
            get
            {
                return ResourceManager.GetString("General_SucessText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to failed Text!!.
        /// </summary>
        public static string General_FailedError
        {
            get
            {
                return ResourceManager.GetString("General_FailedError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to successfully deleted Text!!.
        /// </summary>
        public static string General_SuccessDeleteText
        {
            get
            {
                return ResourceManager.GetString("General_SuccessDeleteText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to loading Text!!.
        /// </summary>
        public static string General_LoadingText
        {
            get
            {
                return ResourceManager.GetString("General_LoadingText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to uploading Text!!.
        /// </summary>
        public static string General_UploadingProgress
        {
            get
            {
                return ResourceManager.GetString("General_UploadingProgress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to fille the field Text!!.
        /// </summary>
        public static string General_FillAllField
        {
            get
            {
                return ResourceManager.GetString("General_FillAllField", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to RootViewModel MenuText!!.
        /// </summary>
        public static string RootViewModel_MenuText {
            get {
                return ResourceManager.GetString("RootViewModel_MenuText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to later Text!!.
        /// </summary>
        public static string RootViewModel_LaterText
        {
            get
            {
                return ResourceManager.GetString("RootViewModel_LaterText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to update Text!!.
        /// </summary>
        public static string RootViewModel_UpdateText
        {
            get
            {
                return ResourceManager.GetString("RootViewModel_UpdateText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to update available Text!!.
        /// </summary>
        public static string RootViewModel_UpdateAvailableText
        {
            get
            {
                return ResourceManager.GetString("RootViewModel_UpdateAvailableText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to no storage found Text!!.
        /// </summary>
        public static string RootViewModel_NoStorageFoundText
        {
            get
            {
                return ResourceManager.GetString("RootViewModel_NoStorageFoundText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to refresh Text!!.
        /// </summary>
        public static string RootViewModel_RefreshText
        {
            get
            {
                return ResourceManager.GetString("RootViewModel_RefreshText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to sync Text!!.
        /// </summary>
        public static string RootViewModel_SyncText
        {
            get
            {
                return ResourceManager.GetString("RootViewModel_SyncText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to result not found Text!!.
        /// </summary>
        public static string RootViewModel_NoResultFoundText
        {
            get
            {
                return ResourceManager.GetString("RootViewModel_NoResultFoundText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to data sync successful Text!!.
        /// </summary>
        public static string RootViewModel_DataSyncSuccessText
        {
            get
            {
                return ResourceManager.GetString("RootViewModel_DataSyncSuccessText", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to RootViewModel CodeGeneratorText!!.
        ///</summary>
        public static string RootViewModel_CodeGeneratorText {
            get {
                return ResourceManager.GetString("RootViewModel_CodeGeneratorText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to find Text!!.
        ///</summary>
        public static string RootViewModel_FindText
        {
            get
            {
                return ResourceManager.GetString("RootViewModel_FindText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BoxDetailViewModel DeletItemText!!.
        /// </summary>
        public static string BoxDetailViewModel_DeletItemText
        {
            get
            {
                return ResourceManager.GetString("BoxDetailViewModel_DeletItemText", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Looks up a localized string similar to copy ClipboardText!!.
        /// </summary>
        public static string OnboardingViewModel_ClipboardText
        {
            get
            {
                return ResourceManager.GetString("OnboardingViewModel_ClipboardText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MultiIdFromOther Text!!.
        /// </summary>
        public static string OnboardingViewModel_MultiIdFromOtherText
        {
            get
            {
                return ResourceManager.GetString("OnboardingViewModel_MultiIdFromOtherText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DisablingMultiIduser Text!!.
        /// </summary>
        public static string OnboardingViewModel_DisablingMultiIduserText
        {
            get
            {
                return ResourceManager.GetString("OnboardingViewModel_DisablingMultiIduserText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Done Text!!.
        /// </summary>
        public static string OnboardingViewModel_DoneButtText
        {
            get
            {
                return ResourceManager.GetString("OnboardingViewModel_DoneButtText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CheckValidMultiId Text!!.
        /// </summary>
        public static string OnboardingViewModel_CheckValidMultiId
        {
            get
            {
                return ResourceManager.GetString("OnboardingViewModel_CheckValidMultiId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create One Text!!.
        /// </summary>
        public static string OnboardingViewModel_CreateOne
        {
            get
            {
                return ResourceManager.GetString("OnboardingViewModel_CreateOne", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Valid MultiId Error Text!!.
        /// </summary>
        public static string OnboardingViewModel_ValidMultiIdError
        {
            get
            {
                return ResourceManager.GetString("OnboardingViewModel_ValidMultiIdError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to InvalidId Error Text!!.
        /// </summary>
        public static string OnboardingViewModel_InvalidIdError
        {
            get
            {
                return ResourceManager.GetString("OnboardingViewModel_InvalidIdError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AlreadyId Error Text!!.
        /// </summary>
        public static string OnboardingViewModel_AlreadyIdError
        {
            get
            {
                return ResourceManager.GetString("OnboardingViewModel_AlreadyIdError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ClearDataSaved Text!!.
        /// </summary>
        public static string OnboardingViewModel_ClearDataSaved
        {
            get
            {
                return ResourceManager.GetString("OnboardingViewModel_ClearDataSaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SettingMultiIdError Text!!.
        /// </summary>
        public static string OnboardingViewModel_SettingMultiIdError
        {
            get
            {
                return ResourceManager.GetString("OnboardingViewModel_SettingMultiIdError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Downloading Text!!.
        /// </summary>
        public static string OnboardingViewModel_DownloadingText
        {
            get
            {
                return ResourceManager.GetString("OnboardingViewModel_DownloadingText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Downloading Failed Text!!.
        /// </summary>
        public static string OnboardingViewModel_DownloadFailed
        {
            get
            {
                return ResourceManager.GetString("OnboardingViewModel_DownloadFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SubscriptionError Text!!.
        /// </summary>
        public static string OnboardingViewModel_SubscriptionError
        {
            get
            {
                return ResourceManager.GetString("OnboardingViewModel_SubscriptionError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to QRcode Text!!.
        /// </summary>
        public static string CodeGeneratorViewModel_QRcodeText
        {
            get
            {
                return ResourceManager.GetString("CodeGeneratorViewModel_QRcodeText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to barcode Text!!.
        /// </summary>
        public static string CodeGeneratorViewModel_BarcodeText
        {
            get
            {
                return ResourceManager.GetString("CodeGeneratorViewModel_BarcodeText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MissingTitle Text!!.
        /// </summary>
        public static string CodeGeneratorViewModel_MissingTitle
        {
            get
            {
                return ResourceManager.GetString("CodeGeneratorViewModel_MissingTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SelectCode Text!!.
        /// </summary>
        public static string CodeGeneratorViewModel_SelectCode
        {
            get
            {
                return ResourceManager.GetString("CodeGeneratorViewModel_SelectCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SelectPage Text!!.
        /// </summary>
        public static string CodeGeneratorViewModel_SelectPage
        {
            get
            {
                return ResourceManager.GetString("CodeGeneratorViewModel_SelectPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to save Basket Successful Text!!.
        /// </summary>
        public static string PaperProductViewModel_BasketSuccess
        {
            get
            {
                return ResourceManager.GetString("PaperProductViewModel_BasketSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to save ErrorSaveItem Text!!.
        /// </summary>
        public static string PaperProductViewModel_ErrorSaveItem
        {
            get
            {
                return ResourceManager.GetString("PaperProductViewModel_ErrorSaveItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to StandardPack48QRTitle Text!!.
        /// </summary>
        public static string SelectProductViewModel_StandardPack48QRTitle
        {
            get
            {
                return ResourceManager.GetString("SelectProductViewModel_StandardPack48QRTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to StandardPack48QrTitle Text!!.
        /// </summary>
        public static string SelectProductViewModel_StandardPack48BrTitle
        {
            get
            {
                return ResourceManager.GetString("SelectProductViewModel_StandardPack48BrTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to StandardPack48BrDiscription Text!!.
        /// </summary>
        public static string SelectProductViewModel_StandardPack48BrDiscription
        {
            get
            {
                return ResourceManager.GetString("SelectProductViewModel_StandardPack48BrDiscription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to StandardPack48BrPrice Text!!.
        /// </summary>
        public static string SelectProductViewModel_StandardPack48BrPrice
        {
            get
            {
                return ResourceManager.GetString("SelectProductViewModel_StandardPack48BrPrice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to StandardPack Discription Text!!.
        /// </summary>
        public static string SelectProductViewModel_StandardPack48QRDiscription
        {
            get
            {
                return ResourceManager.GetString("SelectProductViewModel_StandardPack48QRDiscription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LargePack100QRTitle Text!!.
        /// </summary>
        public static string SelectProductViewModel_LargePack100QRTitle
        {
            get
            {
                return ResourceManager.GetString("SelectProductViewModel_LargePack100QRTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LargePack100QRDiscription Text!!.
        /// </summary>
        public static string SelectProductViewModel_LargePack100QRDiscription
        {
            get
            {
                return ResourceManager.GetString("SelectProductViewModel_LargePack100QRDiscription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LargePack100QRPrice Text!!.
        /// </summary>
        public static string SelectProductViewModel_LargePack100QRPrice
        {
            get
            {
                return ResourceManager.GetString("SelectProductViewModel_LargePack100QRPrice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to StandardPack Price Text!!.
        /// </summary>
        public static string SelectProductViewModel_StandardPack48QRPrice
        {
            get
            {
                return ResourceManager.GetString("SelectProductViewModel_StandardPack48QRPrice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New Text!!.
        /// </summary>
        public static string SelectProductViewModel_NewText
        {
            get
            {
                return ResourceManager.GetString("SelectProductViewModel_NewText", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Buy Text!!.
        /// </summary>
        public static string AddToBasketViewModel_BuyText
        {
            get
            {
                return ResourceManager.GetString("AddToBasketViewModel_BuyText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DeleteFromBasket Text!!.
        /// </summary>
        public static string AddToBasketViewModel_DeleteFromBasket
        {
            get
            {
                return ResourceManager.GetString("AddToBasketViewModel_DeleteFromBasket", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IBANCopied Text!!.
        /// </summary>
        public static string BankTransferViewModel_IBANCopiedText
        {
            get
            {
                return ResourceManager.GetString("BankTransferViewModel_IBANCopiedText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ReferenceCopied  Text!!.
        /// </summary>
        public static string BankTransferViewModel_ReferenceCopiedText
        {
            get
            {
                return ResourceManager.GetString("BankTransferViewModel_ReferenceCopiedText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EmailSendMssg Text!!.
        /// </summary>
        public static string BankTransferViewModel_EmailSendMssg
        {
            get
            {
                return ResourceManager.GetString("BankTransferViewModel_EmailSendMssg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SaveErrorMsg Text!!.
        /// </summary>
        public static string BankTransferViewModel_SaveErrorMsg
        {
            get
            {
                return ResourceManager.GetString("BankTransferViewModel_SaveErrorMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar togenerate codes Text!!.
        /// </summary>
        public static string SelectProductViewModel_GenrateOfA4QRcodeTitle
        {
            get
            {
                return ResourceManager.GetString("SelectProductViewModel_GenrateOfA4QRcodeTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar togenerate select codes Text!!.
        /// </summary>
        public static string SelectProductViewModel_GenrateOfA4QRcodeColor
        {
            get
            {
                return ResourceManager.GetString("SelectProductViewModel_GenrateOfA4QRcodeColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar togenerate select codes Text!!.
        /// </summary>
        public static string SelectProductViewModel_GenrateOfA4QRcodePrice
        {
            get
            {
                return ResourceManager.GetString("SelectProductViewModel_GenrateOfA4QRcodePrice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar togenerate FillField Text!!.
        /// </summary>
        public static string PaymentShipmentViewModel_FillFieldText
        {
            get
            {
                return ResourceManager.GetString("PaymentShipmentViewModel_FillFieldText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar togenerate Invalid Text!!.
        /// </summary>
        public static string PaymentShipmentViewModel_InvalidText
        {
            get
            {
                return ResourceManager.GetString("PaymentShipmentViewModel_InvalidText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar togenerate enter email Text!!.
        /// </summary>
        public static string PaymentShipmentViewModel_EnterEmailText
        {
            get
            {
                return ResourceManager.GetString("PaymentShipmentViewModel_EnterEmailText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar togenerate FailedPayment Text!!.
        /// </summary>
        public static string PaymentShipmentViewModel_FailedPayment
        {
            get
            {
                return ResourceManager.GetString("PaymentShipmentViewModel_FailedPayment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar togenerate UnexpectedPayment Text!!.
        /// </summary>
        public static string PaymentShipmentViewModel_UnexpectedPayment
        {
            get
            {
                return ResourceManager.GetString("PaymentShipmentViewModel_UnexpectedPayment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar togenerate order received Text!!.
        /// </summary>
        public static string PaymentShipmentViewModel_OrderReceived
        {
            get
            {
                return ResourceManager.GetString("PaymentShipmentViewModel_OrderReceived", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar togenerate unexpected error Text!!.
        /// </summary>
        public static string PaymentShipmentViewModel_UnexpectedErrorText
        {
            get
            {
                return ResourceManager.GetString("PaymentShipmentViewModel_UnexpectedErrorText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar togenerate genrate code msg Text!!.
        /// </summary>
        public static string PaymentShipmentViewModel_GeneratedCodeMsg
        {
            get
            {
                return ResourceManager.GetString("PaymentShipmentViewModel_GeneratedCodeMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar togenerate sharing msg Text!!.
        /// </summary>
        public static string SubscriptionViewModel_SharingMsgText
        {
            get
            {
                return ResourceManager.GetString("SubscriptionViewModel_SharingMsgText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar togenerate unlimited Text!!.
        /// </summary>
        public static string SubscriptionViewModel_UnlimitedText
        {
            get
            {
                return ResourceManager.GetString("SubscriptionViewModel_UnlimitedText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar togenerate cloud Text!!.
        /// </summary>
        public static string SubscriptionViewModel_CloudBackText
        {
            get
            {
                return ResourceManager.GetString("SubscriptionViewModel_CloudBackText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar move item Text!!.
        /// </summary>
        public static string SubscriptionViewModel_MoveItemText
        {
            get
            {
                return ResourceManager.GetString("SubscriptionViewModel_MoveItemText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar multiple Text!!.
        /// </summary>
        public static string SubscriptionViewModel_MultipleImagesText
        {
            get
            {
                return ResourceManager.GetString("SubscriptionViewModel_MultipleImagesText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar advertisements Text!!.
        /// </summary>
        public static string SubscriptionViewModel_AdvertisementsText
        {
            get
            {
                return ResourceManager.GetString("SubscriptionViewModel_AdvertisementsText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar premium Text!!.
        /// </summary>
        public static string SubscriptionViewModel_PremiumActiveMsg
        {
            get
            {
                return ResourceManager.GetString("SubscriptionViewModel_PremiumActiveMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar unlok features Text!!.
        /// </summary>
        public static string SubscriptionViewModel_UnlockFeaturesText
        {
            get
            {
                return ResourceManager.GetString("SubscriptionViewModel_UnlockFeaturesText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar wait payment Text!!.
        /// </summary>
        public static string SubscriptionViewModel_WaitingPaymentText
        {
            get
            {
                return ResourceManager.GetString("SubscriptionViewModel_WaitingPaymentText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar enter email Text!!.
        /// </summary>
        public static string SubscriptionViewModel_EnterEmailText
        {
            get
            {
                return ResourceManager.GetString("SubscriptionViewModel_EnterEmailText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar failed payment Text!!.
        /// </summary>
        public static string SubscriptionViewModel_FailedPaymentText
        {
            get
            {
                return ResourceManager.GetString("SubscriptionViewModel_FailedPaymentText", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar completed payment Text!!.
        /// </summary>
        public static string SubscriptionViewModel_PaymentCompletedText
        {
            get
            {
                return ResourceManager.GetString("SubscriptionViewModel_PaymentCompletedText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar active premium Text!!.
        /// </summary>
        public static string SubscriptionViewModel_ActivePremiumText
        {
            get
            {
                return ResourceManager.GetString("SubscriptionViewModel_ActivePremiumText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar subscription cancel Text!!.
        /// </summary>
        public static string SubscriptionViewModel_SubscriptiontCancelText
        {
            get
            {
                return ResourceManager.GetString("SubscriptionViewModel_SubscriptiontCancelText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar montly cost Text!!.
        /// </summary>
        public static string SubscriptionViewModel_MonthSelectedEuroCurrencyText
        {
            get
            {
                return ResourceManager.GetString("SubscriptionViewModel_MonthSelectedEuroCurrencyText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar doller Text!!.
        /// </summary>
        public static string SubscriptionViewModel_MonthSelectedDollerCurrencyText
        {
            get
            {
                return ResourceManager.GetString("SubscriptionViewModel_MonthSelectedDollerCurrencyText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar varifying Text!!.
        /// </summary>
        public static string SubscriptionViewModel_VerifyingPaymentText
        {
            get
            {
                return ResourceManager.GetString("SubscriptionViewModel_VerifyingPaymentText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar copy id Text!!.
        /// </summary>
        public static string YoursOrdersViewModel_CopyId
        {
            get
            {
                return ResourceManager.GetString("YoursOrdersViewModel_CopyId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar copy clipboard Text!!.
        /// </summary>
        public static string YoursOrdersViewModel_CopyToClipboard
        {
            get
            {
                return ResourceManager.GetString("YoursOrdersViewModel_CopyToClipboard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar location placeholder Text!!.
        /// </summary>
        public static string BoxDetailViewModel_LocationPlaceText
        {
            get
            {
                return ResourceManager.GetString("BoxDetailViewModel_LocationPlaceText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar category placeholder Text!!.
        /// </summary>
        public static string BoxDetailViewModel_CategoryPlaceText
        {
            get
            {
                return ResourceManager.GetString("BoxDetailViewModel_CategoryPlaceText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar category Text!!.
        /// </summary>
        public static string BoxDetailViewModel_CategoryText
        {
            get
            {
                return ResourceManager.GetString("BoxDetailViewModel_CategoryText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar field empty Text!!.
        /// </summary>
        public static string BoxDetailViewModel_LeftEmptyText
        {
            get
            {
                return ResourceManager.GetString("BoxDetailViewModel_LeftEmptyText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar item not found Text!!.
        /// </summary>
        public static string BoxDetailViewModel_ItemNotFoundText
        {
            get
            {
                return ResourceManager.GetString("BoxDetailViewModel_ItemNotFoundText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar item not possible to delete Text!!.
        /// </summary>
        public static string BoxDetailViewModel_NotPossibleToDelete
        {
            get
            {
                return ResourceManager.GetString("YoursOrdersViewModel_NotPossibleToDelete", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar item could not be deleted error Text!!.
        /// </summary>
        public static string BoxDetailViewModel_UnexpectedDeleteError
        {
            get
            {
                return ResourceManager.GetString("YoursOrdersViewModel_UnexpectedDeleteError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar item could not be already selected Text!!.
        /// </summary>
        public static string BoxDetailViewModel_AlreadySelectedText
        {
            get
            {
                return ResourceManager.GetString("BoxDetailViewModel_AlreadySelectedText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar item could not be target box Text!!.
        /// </summary>
        public static string BoxDetailViewModel_TargetBox
        {
            get
            {
                return ResourceManager.GetString("BoxDetailViewModel_TargetBox", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar item could not be moving Text!!.
        /// </summary>
        public static string BoxDetailViewModel_Moving
        {
            get
            {
                return ResourceManager.GetString("BoxDetailViewModel_Moving", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar data move error Text!!.
        /// </summary>
        public static string BoxDetailViewModel_MovedError
        {
            get
            {
                return ResourceManager.GetString("BoxDetailViewModel_MovedError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar successfully moved Text!!.
        /// </summary>
        public static string BoxDetailViewModel_SuccessMoved
        {
            get
            {
                return ResourceManager.GetString("BoxDetailViewModel_SuccessMoved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar error moved Text!!.
        /// </summary>
        public static string BoxDetailViewModel_ErrorMoving
        {
            get
            {
                return ResourceManager.GetString("BoxDetailViewModel_ErrorMoving", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar item name Text!!.
        /// </summary>
        public static string ItemDetailViewModel_ItemName
        {
            get
            {
                return ResourceManager.GetString("ItemDetailViewModel_ItemName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar enter name Text!!.
        /// </summary>
        public static string ItemDetailViewModel_EnterNamePlace
        {
            get
            {
                return ResourceManager.GetString("ItemDetailViewModel_EnterNamePlace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar remarks Text!!.
        /// </summary>
        public static string ItemDetailViewModel_Remarks
        {
            get
            {
                return ResourceManager.GetString("ItemDetailViewModel_Remarks", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar more info Text!!.
        /// </summary>
        public static string ItemDetailViewModel_MoreInfo
        {
            get
            {
                return ResourceManager.GetString("ItemDetailViewModel_MoreInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar camera permission Text!!.
        /// </summary>
        public static string ItemDetailViewModel_CameraPermission
        {
            get
            {
                return ResourceManager.GetString("ItemDetailViewModel_CameraPermission", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar could not capture Text!!.
        /// </summary>
        public static string ItemDetailViewModel_NotCapture
        {
            get
            {
                return ResourceManager.GetString("ItemDetailViewModel_NotCapture", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar max. image added Text!!.
        /// </summary>
        public static string ItemDetailViewModel_ImageAdded
        {
            get
            {
                return ResourceManager.GetString("ItemDetailViewModel_ImageAdded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar not able to pick images Text!!.
        /// </summary>
        public static string ItemDetailViewModel_NotAbleToPick
        {
            get
            {
                return ResourceManager.GetString("ItemDetailViewModel_NotAbleToPick", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar empty field error Text!!.
        /// </summary>
        public static string ItemDetailViewModel_EmptyFieldError
        {
            get
            {
                return ResourceManager.GetString("ItemDetailViewModel_EmptyFieldError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar atleast add one image Text!!.
        /// </summary>
        public static string ItemDetailViewModel_AddOneImage
        {
            get
            {
                return ResourceManager.GetString("ItemDetailViewModel_AddOneImage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar not able to retrieve data Text!!.
        /// </summary>
        public static string ItemDetailViewModel_NotAbleToRetrieveData
        {
            get
            {
                return ResourceManager.GetString("ItemDetailViewModel_NotAbleToRetrieveData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar item not found Text!!.
        /// </summary>
        public static string ItemDetailViewModel_ItemNotFound
        {
            get
            {
                return ResourceManager.GetString("ItemDetailViewModel_ItemNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar can not be modified Text!!.
        /// </summary>
        public static string ItemDetailViewModel_CanNotBeModified
        {
            get
            {
                return ResourceManager.GetString("ItemDetailViewModel_CanNotBeModified", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar successfully update Text!!.
        /// </summary>
        public static string ItemDetailViewModel_SuccessfullyUpdate
        {
            get
            {
                return ResourceManager.GetString("ItemDetailViewModel_SuccessfullyUpdate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar data could not be update Text!!.
        /// </summary>
        public static string ItemDetailViewModel_DataCouldNotUpdate
        {
            get
            {
                return ResourceManager.GetString("ItemDetailViewModel_DataCouldNotUpdate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar unexpected error Text!!.
        /// </summary>
        public static string ItemDetailViewModel_UnexpectedErrorUpdate
        {
            get
            {
                return ResourceManager.GetString("ItemDetailViewModel_UnexpectedErrorUpdate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar unexpected storage Text!!.
        /// </summary>
        public static string ItemDetailViewModel_UnexpectedStorage
        {
            get
            {
                return ResourceManager.GetString("ItemDetailViewModel_UnexpectedStorage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar item already exist Text!!.
        /// </summary>
        public static string ItemDetailViewModel_ItemAlreadyExists
        {
            get
            {
                return ResourceManager.GetString("ItemDetailViewModel_ItemAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar item successful saved Text!!.
        /// </summary>
        public static string ItemDetailViewModel_SuccessSaved
        {
            get
            {
                return ResourceManager.GetString("ItemDetailViewModel_SuccessSaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar data could not be saved Text!!.
        /// </summary>
        public static string Dialog_DataCouldNoBeSaved
        {
            get
            {
                return ResourceManager.GetString("Dialog_DataCouldNoBeSaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar unexpected processing error Text!!.
        /// </summary>
        public static string ItemDetailViewModel_UnexpectedErrorProcessing
        {
            get
            {
                return ResourceManager.GetString("ItemDetailViewModel_UnexpectedErrorProcessing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar one 1mb data Text!!.
        /// </summary>
        public static string ItemDetailViewModel_OneMBData
        {
            get
            {
                return ResourceManager.GetString("ItemDetailViewModel_OneMBData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar camera permission Text!!.
        /// </summary>
        public static string ItemDetailViewModel_CameraPermissionRequired
        {
            get
            {
                return ResourceManager.GetString("ItemDetailViewModel_CameraPermissionRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar open setting Text!!.
        /// </summary>
        public static string ItemDetailViewModel_OpenSettings
        {
            get
            {
                return ResourceManager.GetString("ItemDetailViewModel_OpenSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar camera restricted Text!!.
        /// </summary>
        public static string QrBrScannerViewModel_CameraRestricted
        {
            get
            {
                return ResourceManager.GetString("QrBrScannerViewModel_CameraRestricted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar invalid code Text!!.
        /// </summary>
        public static string QrBrScannerViewModel_InvalidCodes
        {
            get
            {
                return ResourceManager.GetString("QrBrScannerViewModel_InvalidCodes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar pick image Text!!.
        /// </summary>
        public static string FilePickerService_PickImage
        {
            get
            {
                return ResourceManager.GetString("FilePickerService_PickImage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string  data sync successful Text!!.
        /// </summary>
        public static string SettingViewModel_DataSync
        {
            get
            {
                return ResourceManager.GetString("SettingViewModel_DataSync", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string  data failed to sync Text!!.
        /// </summary>
        public static string SettingViewModel_FailedDataSync
        {
            get
            {
                return ResourceManager.GetString("SettingViewModel_FailedDataSync", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string  data multiuser Text!!.
        /// </summary>
        public static string MenuViewModel_MultiuserText
        {
            get
            {
                return ResourceManager.GetString("MenuViewModel_MultiuserText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string subscribe Text!!.
        /// </summary>
        public static string MenuViewModel_SubscribeText
        {
            get
            {
                return ResourceManager.GetString("MenuViewModel_SubscribeText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string share Text!!.
        /// </summary>
        public static string MenuViewModel_ShareText
        {
            get
            {
                return ResourceManager.GetString("MenuViewModel_ShareText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string basket Text!!.
        /// </summary>
        public static string MenuViewModel_BasketText
        {
            get
            {
                return ResourceManager.GetString("MenuViewModel_BasketText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string your orders Text!!.
        /// </summary>
        public static string MenuViewModel_YourOrderText
        {
            get
            {
                return ResourceManager.GetString("MenuViewModel_YourOrderText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string setting Text!!.
        /// </summary>
        public static string MenuViewModel_SettingText
        {
            get
            {
                return ResourceManager.GetString("MenuViewModel_SettingText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string feedback Text!!.
        /// </summary>
        public static string MenuViewModel_FeedbackText
        {
            get
            {
                return ResourceManager.GetString("MenuViewModel_FeedbackText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string select barcode Text!!.
        /// </summary>
        public static string DialogMoveToViewModel_SelectBarcode
        {
            get
            {
                return ResourceManager.GetString("DialogMoveToViewModel_SelectBarcode", resourceCulture);
            }
        }

    }
}
