//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QrSortable.Components.UiFunctionality.Localization
 {
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {}
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QrSortable.Components.UiFunctionality.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Dialog InternetConnection Message Text!!.
        /// </summary>
        public static string Dialog_InternetConnection_Message
        {
            get
            {
                return ResourceManager.GetString("Dialog_InternetConnection_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog InternetConnection Title Text!!.
        /// </summary>
        public static string Dialog_InternetConnection_Title
        {
            get
            {
                return ResourceManager.GetString("Dialog_InternetConnection_Title", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Dialog ConfirmationMessage Text!!.
        /// </summary>
        public static string Dialog_ConfirmationMessage_Text
        {
            get
            {
                return ResourceManager.GetString("Dialog_ConfirmationMessage_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog information Text!!.
        /// </summary>
        public static string Dialog_InformationText
        {
            get
            {
                return ResourceManager.GetString("Dialog_InformationText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog Error Text!!.
        /// </summary>
        public static string Dialog_Error
        {
            get
            {
                return ResourceManager.GetString("Dialog_Error", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Dialog Cancel Text!!.
        /// </summary>
        public static string Dialog_Cancel_Text
        {
            get
            {
                return ResourceManager.GetString("Dialog_Cancel_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dialog OK Text!!.
        /// </summary>
        public static string Dialog_OK_Text
        {
            get
            {
                return ResourceManager.GetString("Dialog_OK_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RootViewModel MenuText!!.
        /// </summary>
        public static string RootViewModel_MenuText {
            get {
                return ResourceManager.GetString("RootViewModel_MenuText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RootViewModel CodeGeneratorText!!.
        ///</summary>
        public static string RootViewModel_CodeGeneratorText {
            get {
                return ResourceManager.GetString("RootViewModel_CodeGeneratorText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BoxDetailViewModel DeletItemText!!.
        /// </summary>
        public static string BoxDetailViewModel_DeletItemText
        {
            get
            {
                return ResourceManager.GetString("BoxDetailViewModel_DeletItemText", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Looks up a localized string similar to copy ClipboardText!!.
        /// </summary>
        public static string OnboardingViewModel_ClipboardText
        {
            get
            {
                return ResourceManager.GetString("OnboardingViewModel_ClipboardText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MultiIdFromOther Text!!.
        /// </summary>
        public static string OnboardingViewModel_MultiIdFromOtherText
        {
            get
            {
                return ResourceManager.GetString("OnboardingViewModel_MultiIdFromOtherText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DisablingMultiIduser Text!!.
        /// </summary>
        public static string OnboardingViewModel_DisablingMultiIduserText
        {
            get
            {
                return ResourceManager.GetString("OnboardingViewModel_DisablingMultiIduserText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Done Text!!.
        /// </summary>
        public static string OnboardingViewModel_DoneButtText
        {
            get
            {
                return ResourceManager.GetString("OnboardingViewModel_DoneButtText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CheckValidMultiId Text!!.
        /// </summary>
        public static string OnboardingViewModel_CheckValidMultiId
        {
            get
            {
                return ResourceManager.GetString("OnboardingViewModel_CheckValidMultiId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create One Text!!.
        /// </summary>
        public static string OnboardingViewModel_CreateOne
        {
            get
            {
                return ResourceManager.GetString("OnboardingViewModel_CreateOne", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Valid MultiId Error Text!!.
        /// </summary>
        public static string OnboardingViewModel_ValidMultiIdError
        {
            get
            {
                return ResourceManager.GetString("OnboardingViewModel_ValidMultiIdError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to InvalidId Error Text!!.
        /// </summary>
        public static string OnboardingViewModel_InvalidIdError
        {
            get
            {
                return ResourceManager.GetString("OnboardingViewModel_InvalidIdError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AlreadyId Error Text!!.
        /// </summary>
        public static string OnboardingViewModel_AlreadyIdError
        {
            get
            {
                return ResourceManager.GetString("OnboardingViewModel_AlreadyIdError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ClearDataSaved Text!!.
        /// </summary>
        public static string OnboardingViewModel_ClearDataSaved
        {
            get
            {
                return ResourceManager.GetString("OnboardingViewModel_ClearDataSaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SettingMultiIdError Text!!.
        /// </summary>
        public static string OnboardingViewModel_SettingMultiIdError
        {
            get
            {
                return ResourceManager.GetString("OnboardingViewModel_SettingMultiIdError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Downloading Text!!.
        /// </summary>
        public static string OnboardingViewModel_DownloadingText
        {
            get
            {
                return ResourceManager.GetString("OnboardingViewModel_DownloadingText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Downloading Failed Text!!.
        /// </summary>
        public static string OnboardingViewModel_DownloadFailed
        {
            get
            {
                return ResourceManager.GetString("OnboardingViewModel_DownloadFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SubscriptionError Text!!.
        /// </summary>
        public static string OnboardingViewModel_SubscriptionError
        {
            get
            {
                return ResourceManager.GetString("OnboardingViewModel_SubscriptionError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to QRcode Text!!.
        /// </summary>
        public static string CodeGeneratorViewModel_QRcodeText
        {
            get
            {
                return ResourceManager.GetString("CodeGeneratorViewModel_QRcodeText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to barcode Text!!.
        /// </summary>
        public static string CodeGeneratorViewModel_BarcodeText
        {
            get
            {
                return ResourceManager.GetString("CodeGeneratorViewModel_BarcodeText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MissingTitle Text!!.
        /// </summary>
        public static string CodeGeneratorViewModel_MissingTitle
        {
            get
            {
                return ResourceManager.GetString("CodeGeneratorViewModel_MissingTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SelectCode Text!!.
        /// </summary>
        public static string CodeGeneratorViewModel_SelectCode
        {
            get
            {
                return ResourceManager.GetString("CodeGeneratorViewModel_SelectCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SelectPage Text!!.
        /// </summary>
        public static string CodeGeneratorViewModel_SelectPage
        {
            get
            {
                return ResourceManager.GetString("CodeGeneratorViewModel_SelectPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to save Basket Successful Text!!.
        /// </summary>
        public static string PaperProductViewModel_BasketSuccess
        {
            get
            {
                return ResourceManager.GetString("PaperProductViewModel_BasketSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to save ErrorSaveItem Text!!.
        /// </summary>
        public static string PaperProductViewModel_ErrorSaveItem
        {
            get
            {
                return ResourceManager.GetString("PaperProductViewModel_ErrorSaveItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SetOfA4QRcodeTitle Text!!.
        /// </summary>
        public static string SelectProductViewModel_SetOfA4QRcodeTitle
        {
            get
            {
                return ResourceManager.GetString("SelectProductViewModel_SetOfA4QRcodeTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SetOfA4QRcodeDiscription Text!!.
        /// </summary>
        public static string SelectProductViewModel_SetOfA4QRcodeDiscription
        {
            get
            {
                return ResourceManager.GetString("SelectProductViewModel_SetOfA4QRcodeDiscription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SetOfA4QRcodePrice Text!!.
        /// </summary>
        public static string SelectProductViewModel_SetOfA4QRcodePrice
        {
            get
            {
                return ResourceManager.GetString("SelectProductViewModel_SetOfA4QRcodePrice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New Text!!.
        /// </summary>
        public static string SelectProductViewModel_NewText
        {
            get
            {
                return ResourceManager.GetString("SelectProductViewModel_NewText", resourceCulture);
            }
        }

    }
}
