// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QrSortable.Components.CoreFeatures.DataManagement.General;

#nullable disable

namespace QrSortable.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241216140945_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("QrSortable.Components.CoreFeatures.DataManagement.General.Models.GeneralInformation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotificationPermissionStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OnboardingProgress")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("GeneralInformation");
                });

            modelBuilder.Entity("QrSortable.Components.CoreFeatures.DataManagement.General.Models.StorageEntry", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BarcodeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BarcodeValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StorageId")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("StorageEntries");
                });

            modelBuilder.Entity("QrSortable.Components.CoreFeatures.DataManagement.General.Models.UserInfos", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUserLogedIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAvatar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("UserInformation");
                });

            modelBuilder.Entity("QrSortable.Components.CoreFeatures.DataManagement.General.Models.StorageEntry", b =>
                {
                    b.OwnsMany("QrSortable.Components.CoreFeatures.DataManagement.General.Models.Item", "Items", b1 =>
                        {
                            b1.Property<int>("StorageEntryID")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.PrimitiveCollection<string>("ImagesFilePath")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("ItemName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("StorageEntryID", "Id");

                            b1.ToTable("Item");

                            b1.WithOwner()
                                .HasForeignKey("StorageEntryID");
                        });

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
