// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QrSortable.Components.CoreFeatures.DataManagement.General;

#nullable disable

namespace QrSortable.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("QrSortable.Components.CoreFeatures.DataManagement.General.Models.GeneralInformation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotificationPermissionStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OnboardingProgress")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("GeneralInformation");
                });

            modelBuilder.Entity("QrSortable.Components.CoreFeatures.DataManagement.General.Models.UserInfos", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUserLogedIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAvatar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("UserInformation");
                });
#pragma warning restore 612, 618
        }
    }
}
