// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace QrSortable.Components.CoreFeatures.DataManagement.Backend.CompiledModels
{
    public partial class BackendDatabaseContextModel
    {
        private BackendDatabaseContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("e035baad-bd9e-4aa4-b7d4-792109f2b26c"), entityTypeCount: 2)
        {
        }

        partial void Initialize()
        {
            var dtoOrdersModel = DtoOrdersModelEntityType.Create(this);
            var dtoStorageEntryModel = DtoStorageEntryModelEntityType.Create(this);

            DtoOrdersModelEntityType.CreateAnnotations(dtoOrdersModel);
            DtoStorageEntryModelEntityType.CreateAnnotations(dtoStorageEntryModel);

            AddAnnotation("ProductVersion", "9.0.0");
        }
    }
}
