// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using QrSortable.Components.CoreFeatures.DataManagement.Backend;
using QrSortable.Components.CoreFeatures.DataManagement.Backend.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(BackendDatabaseContext), typeof(BackendDatabaseContextModel))]
