// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using QrSortable.Components.CoreFeatures.DataManagement.General;
using QrSortable.Components.CoreFeatures.DataManagement.General.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(DatabaseContext), typeof(DatabaseContextModel))]
