// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace QrSortable.Components.CoreFeatures.DataManagement.General.CompiledModels
{
    public partial class DatabaseContextModel
    {
        private DatabaseContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("654a51e3-2a70-4758-8fa7-16c1a848d06b"), entityTypeCount: 5)
        {
        }

        partial void Initialize()
        {
            var addToBasketData = AddToBasketDataEntityType.Create(this);
            var generalInformation = GeneralInformationEntityType.Create(this);
            var storageEntry = StorageEntryEntityType.Create(this);
            var userInfos = UserInfosEntityType.Create(this);
            var yoursOrderData = YoursOrderDataEntityType.Create(this);

            AddToBasketDataEntityType.CreateAnnotations(addToBasketData);
            GeneralInformationEntityType.CreateAnnotations(generalInformation);
            StorageEntryEntityType.CreateAnnotations(storageEntry);
            UserInfosEntityType.CreateAnnotations(userInfos);
            YoursOrderDataEntityType.CreateAnnotations(yoursOrderData);

            AddAnnotation("ProductVersion", "9.0.0");
        }
    }
}
