// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.Maui.ApplicationModel;
using QrSortable.Components.CoreFeatures.DataManagement.General.Models;
using QrSortable.Components.CoreFeatures.DataManagement.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace QrSortable.Components.CoreFeatures.DataManagement.General.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class GeneralInformationEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "QrSortable.Components.CoreFeatures.DataManagement.General.Models.GeneralInformation",
                typeof(GeneralInformation),
                baseEntityType,
                propertyCount: 5,
                keyCount: 1);

            var iD = runtimeEntityType.AddProperty(
                "ID",
                typeof(int),
                propertyInfo: typeof(DatabaseEntry).GetProperty("ID", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(DatabaseEntry).GetField("<ID>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);

            var isBackendUsed = runtimeEntityType.AddProperty(
                "IsBackendUsed",
                typeof(bool),
                propertyInfo: typeof(GeneralInformation).GetProperty("IsBackendUsed", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GeneralInformation).GetField("<IsBackendUsed>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var multiUserId = runtimeEntityType.AddProperty(
                "MultiUserId",
                typeof(string),
                propertyInfo: typeof(GeneralInformation).GetProperty("MultiUserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GeneralInformation).GetField("<MultiUserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var notificationPermissionStatus = runtimeEntityType.AddProperty(
                "NotificationPermissionStatus",
                typeof(PermissionStatus),
                propertyInfo: typeof(GeneralInformation).GetProperty("NotificationPermissionStatus", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GeneralInformation).GetField("<NotificationPermissionStatus>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            notificationPermissionStatus.SetSentinelFromProviderValue(0);

            var onboardingProgress = runtimeEntityType.AddProperty(
                "OnboardingProgress",
                typeof(OnboardingProgress),
                propertyInfo: typeof(GeneralInformation).GetProperty("OnboardingProgress", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(GeneralInformation).GetField("<OnboardingProgress>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            onboardingProgress.SetSentinelFromProviderValue(0);

            var key = runtimeEntityType.AddKey(
                new[] { iD });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "GeneralInformation");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
